{{- if .Values.relay.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.fullname" . }}-relay
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.relay.labels" . | nindent 4 }}
spec:
  type: {{ .Values.relay.service.type }}
  ports:
    - port: {{ .Values.relay.service.port }}
      targetPort: {{ .Values.relay.service.name }}
      protocol: TCP
      name: {{ .Values.relay.service.name }}
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "netbird.relay.selectorLabels" . | nindent 4 }}
{{- end }}
