apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "netbird.name" . }}-monitor
  namespace: {{ include "netbird.namespace" . }}
  labels:
{{- include "netbird.common.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "netbird.name" . }}-monitor
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      interval: 30s # TODO: inject from values
